variables:
  CODECOV_TOKEN: "ccd0e0ce-a5bd-4219-b6cc-c789dca79be1"
  _R_CHECK_CRAN_INCOMING_: "false"
  _R_CHECK_FORCE_SUGGESTS_: "true"
  APT_PKGS: "libcurl4-openssl-dev libssh2-1-dev libssl-dev libxml2-dev zlib1g-dev git"

pages:
  stage: build
  image: alpine:latest
  script:
    - mkdir public/img
    - cp img/hex-logo.png public/img/hex-logo.png
  artifacts:
    paths:
    - public
  only:
  - master

devtools-check:
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends ${APT_PKGS}
    - apt-get install -y --no-install-recommends qpdf pandoc pandoc-citeproc
  stage: test
  image: rocker/tidyverse
  script:
    - R -e 'install.packages(c("yaml", "data.tree", "purrr"))'
    - R -e 'install.packages(c("knitr", "rmarkdown", "covr", "testthat"))'
    - R -e 'devtools::install_gitlab("r-packages/yum")'
    - R -e 'devtools::install_gitlab("r-packages/ufs")'
    - R -e 'devtools::check()'
  tags:
    - docker

coverage:
  stage: deploy
  tags:
    - docker
  image: rocker/tidyverse
  when: on_success
  only:
    - master
  script:
    - R -e 'install.packages(c("data.tree", "yaml", "purrr", "DiagrammeR"))'
    - R -e 'install.packages(c("devtools", "covr", "testthat", "here"))'
    - R -e 'devtools::install_gitlab("r-packages/yum")'
    - R -e 'devtools::install_gitlab("r-packages/ufs")'
    - R -e 'devtools::install()'
    - R -e 'covr::codecov(type = c("tests", "examples"), quiet = FALSE)'
